# -*- coding: utf-8 -*-
"""Time-Series Analysis of Sales & Demand Forecasting_Major_Project.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J34nHyc99m49_l5qACqH2TolBJv5jVrF

**Time-Series Analysis of Sales & Demand Forecasting**

By : Gauri .C. Patil

1. Problem Statement :

   Poor demand forecasting leads to inventory and revenue losses.

2.  Objective :

    Analyze historical sales data and forecast future demand using time-series techniques.
"""

import pandas as pd
import matplotlib.pyplot as plt

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error

"""Step 1 : Load Dataset"""

df = pd.read_csv('/content/sales_data_sample.csv', encoding='latin1')
df.head()

"""Step 2 : Understand the Data"""

df.info()
df.describe()

"""Step 3 : Time-Series Preprocessing"""

df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])
df.set_index('ORDERDATE', inplace=True)
df = df.sort_index()

monthly_sales = df['SALES'].resample('M').sum()
print(monthly_sales.head())

monthly_sales = df['SALES'].resample('ME').sum()
print(monthly_sales.head())

"""Step 4 : Visualize Sales Over Time"""

monthly_sales.plot(title='Sales Over Time')
plt.show()

"""Step 5 : Check Trend & Seasonality (Decomposition)"""

decompose = seasonal_decompose(monthly_sales, model='additive')
decompose.plot()
plt.show()

"""Step 6 : Train-Test Split"""

train_size = len(monthly_sales) - 12
monthly_sales_train = monthly_sales[:train_size]
monthly_sales_test = monthly_sales[train_size:]

"""Step 7 : Build Forecasting Model (ARIMA)"""

model = ARIMA(monthly_sales_train, order=(1,1,1))
model_fit = model.fit()

forecast = model_fit.forecast(steps=12)

"""Step 8 : Forecast Future Demand"""

forecast = model_fit.forecast(steps=12)

plt.figure(figsize=(10,5))
plt.plot(monthly_sales, label="Actual Sales")
plt.plot(forecast, label="Forecasted Sales", color='red')
plt.legend()
plt.show()

"""Step 9 : Forecast Accuracy Evaluation"""

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(monthly_sales[-12:], forecast[:12])
rmse = np.sqrt(mean_squared_error(monthly_sales[-12:], forecast[:12]))

print("MAE:", mae)
print("RMSE:", rmse)

"""**Business Interpretation**

- Helps forecast future demand accurately
- Reduces inventory overstock and stockouts
- Supports data-driven inventory planning

## Conclusion
This project demonstrates how time-series forecasting techniques like ARIMA help businesses predict demand and improve operational decision-making.
"""